apiVersion: v2

name: cloudflared

description: Cyb3r-Jak3's Cloudflared Helm chart

type: application

version: 0.3.16

appVersion: "2025.11.1"

icon: https://public-files.cyberjake.xyz/cloudflare-zero-trust.svg

sources:
  - https://github.com/cloudflare/cloudflared
  - https://github.com/Cyb3r-Jak3/helm-cloudflared

maintainers:
- name: Cyb3r-Jak3
  email: connect@cyberjake.xyz
  url: https://cyberjake.xyz

keywords:
  - cloudflared
  - cloudflare
  - argo
  - tunnel